services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    healthcheck:
      test: ["CMD", "nc","-z","localhost","8080"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 2m
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
